# Site settings
title: Choro.me
email: odk.mmmm@gmail.com
url: https://chromee.github.io
description: 'Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.'
keywords: 'unity, C#, ruby, rails, python'
skills: 'Web-Game Developer'
meta_author: chorome

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: chorome

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 69306D #80B3FF
  primary-rgb: '255,242,173' #"128,179,255"
  secondary: 69306D #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  social: Around the Web
  copyright: chorome

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/mn_chorome
  - title: facebook
    url: https://www.facebook.com/profile.php?id=100009575179002
  - title: github
    url: https://github.com/chromee

vtubers:
  - img: char.webp
    url: https://twitter.com/Charlotte_HNST
  - img: nomu.webp
    url: https://twitter.com/suntory_nomu
  - img: neu.webp
    url: https://twitter.com/mitukineu


# Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
